layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: steve-despres-9b443bb1
  # medium: your_username
  # stackoverflow: your_user_id
   telegram: SteveDsp
   twitter: _SteveD
  # unsplash: your_username
  # vk: your_username
   email: steve.despres@protonmail.com
   xmpp: steve@im.cyberjinh.fr

interests:
  - name: Blockchain
    image_url: https://image.flaticon.com/icons/svg/1660/1660944.svg
  
  - name: Nouvelles technologies
    image_url: https://image.flaticon.com/icons/svg/1238/1238790.svg
  
  - name: Informatique
    image_url: https://image.flaticon.com/icons/svg/123/123400.svg

  - name: Internet
    image_url: https://image.flaticon.com/icons/svg/1164/1164574.svg

  - name: Sécurité
    image_url: https://image.flaticon.com/icons/svg/149/149081.svg

  - name: Privacy
    image_url: https://image.flaticon.com/icons/svg/214/214343.svg

kramdown:  
  parse_block_html: true

pages_list:       
  Centres d'intérêt: '#Interests'
  Projets: '#Projects'